/**
 * Lessico minimo di teste di composto.
 *
 * La regola «il composto prende il genere dell'ultimo elemento» vale al 100%,
 * ma per applicarla bisogna prima SEGMENTARE il composto, e la segmentazione
 * senza lessico non si fa: `Bahnhof` finisce in `-hof` solo se si sa che `Hof`
 * è una parola. Questo elenco copre le teste più frequenti dell'A1-A2; quando
 * il segmentatore non trova nulla, si limita a dirlo invece di inventare.
 *
 * Deliberatamente NON contiene parole che coincidono con suffissi
 * (`-schaft`, `-tät`, `-ur`, `-or`): produrrebbero falsi composti su parole
 * come `Freundschaft`.
 */
import type { Gender } from '../types';

export const NOUN_LEXICON: Readonly<Record<string, Gender>> = {
  // --- der ---
  Hof: 'der',
  Schuh: 'der',
  Tag: 'der',
  Mann: 'der',
  Wagen: 'der',
  Platz: 'der',
  Weg: 'der',
  Punkt: 'der',
  Baum: 'der',
  Berg: 'der',
  Garten: 'der',
  Raum: 'der',
  Tisch: 'der',
  Stuhl: 'der',
  Markt: 'der',
  Preis: 'der',
  Kopf: 'der',
  Wein: 'der',
  Saft: 'der',
  Käse: 'der',
  Zug: 'der',
  Bus: 'der',
  Brief: 'der',
  Freund: 'der',
  Schrank: 'der',
  Teller: 'der',
  Löffel: 'der',
  Schmerz: 'der',
  Schmerzen: 'der',
  Ball: 'der',
  Film: 'der',
  Laden: 'der',
  Schlüssel: 'der',
  Stein: 'der',
  Beruf: 'der',
  Verkehr: 'der',
  Anfang: 'der',
  Abend: 'der',
  Morgen: 'der',
  Monat: 'der',
  Sommer: 'der',
  Winter: 'der',
  Vater: 'der',
  Bruder: 'der',
  Sohn: 'der',
  Hund: 'der',
  Vogel: 'der',
  Fisch: 'der',
  Turm: 'der',
  Ring: 'der',
  Sessel: 'der',

  // --- die ---
  Karte: 'die',
  Zeit: 'die',
  Frau: 'die',
  Stadt: 'die',
  Straße: 'die',
  Tür: 'die',
  Uhr: 'die',
  Bahn: 'die',
  Schule: 'die',
  Küche: 'die',
  Tasche: 'die',
  Milch: 'die',
  Butter: 'die',
  Suppe: 'die',
  Kirche: 'die',
  Bank: 'die',
  Halle: 'die',
  Lampe: 'die',
  Blume: 'die',
  Hand: 'die',
  Nacht: 'die',
  Woche: 'die',
  Stunde: 'die',
  Minute: 'die',
  Arbeit: 'die',
  Wand: 'die',
  Post: 'die',
  Kasse: 'die',
  Nummer: 'die',
  Adresse: 'die',
  Reise: 'die',
  Fahrt: 'die',
  Sprache: 'die',
  Musik: 'die',
  Farbe: 'die',
  Mutter: 'die',
  Schwester: 'die',
  Tochter: 'die',
  Katze: 'die',
  Brücke: 'die',

  // --- das ---
  Ende: 'das',
  Haus: 'das',
  Zimmer: 'das',
  Auto: 'das',
  Buch: 'das',
  Bild: 'das',
  Kind: 'das',
  Wasser: 'das',
  Brot: 'das',
  Glas: 'das',
  Geld: 'das',
  Jahr: 'das',
  Land: 'das',
  Spiel: 'das',
  Werk: 'das',
  Zeug: 'das',
  Fenster: 'das',
  Bett: 'das',
  Tier: 'das',
  Rad: 'das',
  Boot: 'das',
  Schiff: 'das',
  Amt: 'das',
  Zentrum: 'das',
  Wetter: 'das',
  Papier: 'das',
  Heft: 'das',
  Hemd: 'das',
  Kleid: 'das',
  Messer: 'das',
  Fleisch: 'das',
  Gemüse: 'das',
  Obst: 'das',
  Zelt: 'das',
};

/** Teste ordinate dalla più lunga: si cerca sempre il match più specifico. */
export const LEXICON_HEADS_BY_LENGTH: readonly string[] = Object.keys(NOUN_LEXICON).sort(
  (a, b) => b.length - a.length,
);
